### ISSUE TITLE
Unauthorized resource access

### ISSUE THREAD

**Issue by dsavineau** [redhat-cip/python-dciclient#11]
When you try to access to a resource which is not authorized for your team, you get a stack trace because the http return code 412 is not handled correctly.

This is an exemple with topic:

```
$ dcictl topic-show <topic_UUID>
Traceback (most recent call last):
  File "/usr/bin/dcictl", line 9, in <module>
    load_entry_point('dciclient==0.5.1', 'console_scripts', 'dcictl')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/dciclient/v1/shell_commands/topic.py", line 153, in show
  File "build/bdist.linux-x86_64/egg/dciclient/v1/utils.py", line 126, in format_output
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
```

**Comment by dsavineau** [comment]
This issue will be adresses on the api side : https://softwarefactory-project.io/r/#/c/12198/
