### ISSUE TITLE
master code cannot be installed using pip

### ISSUE THREAD

**Issue by mvk** [redhat-cip/python-dciclient#16]
upon installation in isolated env:
````!bash
(myvenv)  makovgan@makovgan-mac > ~/src/github.com/workspace/testenv > pip install git+https://github.com/redhat-cip/python-dciclient.git@master
(myvenv)  makovgan@makovgan-mac > ~/src/github.com/workspace/testenv > dcictl --version
Traceback (most recent call last):
  File "/Users/makovgan/src/github.com/workspace/testenv/myvenv/bin/dcictl", line 5, in <module>
    from dciclient.shell import main
  File "/Users/makovgan/src/github.com/workspace/testenv/myvenv/lib/python3.13/site-packages/dciclient/shell.py", line 19, in <module>
    from dciclient.v1.shell_commands.cli import parse_arguments
  File "/Users/makovgan/src/github.com/workspace/testenv/myvenv/lib/python3.13/site-packages/dciclient/v1/shell_commands/cli.py", line 21, in <module>
    from dciclient.version import __version__
  File "/Users/makovgan/src/github.com/workspace/testenv/myvenv/lib/python3.13/site-packages/dciclient/version.py", line 22, in <module>
    with open(
         ~~~~^
        os.path.join(os.path.dirname(os.path.dirname(__file__)), "python-dciclient.spec")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as f:
    ^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/makovgan/src/github.com/workspace/testenv/myvenv/lib/python3.13/site-packages/python-dciclient.spec'
```

**Comment by fcharlier** [comment]
Hi @mvk, this is expected.

We do [regular releases to pypi](https://pypi.org/project/dciclient/), you should be able to install from there instead of from github:
```
pip install dciclient
```
