### ISSUE TITLE
job-list doesn't work

### ISSUE THREAD

**Issue by goneri** [redhat-cip/python-dciclient#4]
```
(py34)python-dciclient:master* λ http --auth admin:Wr6NAnGhSBNYma http://46.231.133.44/api/v1/jobs
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: Keep-Alive
Content-Length: 509
Content-Type: application/json
Date: Thu, 21 Jan 2016 14:05:53 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_wsgi/3.4 Python/2.7.5

{
    "_meta": {
        "count": 1
    },
    "jobs": [
        {
            "created_at": "2016-01-21T14:04:34.572383",
            "etag": "f09039068c7d783e7547274ce7ff3b41",
            "id": "2203b6f8-8bfe-429c-98d8-678feacb2dbc",
            "jobdefinition_id": "c9467427-a5e8-4e25-9631-c95d62a38cad",
            "recheck": false,
            "remoteci_id": "c3171900-502b-428d-af8b-9011179b41bf",
            "status": "pre-run",
            "team_id": "8bb0a5f7-4864-4fe7-a6fc-e78b179c7a71",
            "updated_at": "2016-01-21T14:05:25.820674"
        }
    ]
}
(py34)python-dciclient:master* λ dcictl job-list
Traceback (most recent call last):
  File "/home/goneri/venv/py34/bin/dcictl", line 9, in <module>
    load_entry_point('dciclient==0.1a1', 'console_scripts', 'dcictl')()
  File "/home/goneri/venv/py34/lib/python3.4/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/goneri/venv/py34/lib/python3.4/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/goneri/venv/py34/lib/python3.4/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/goneri/venv/py34/lib/python3.4/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/goneri/venv/py34/lib/python3.4/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/goneri/venv/py34/lib/python3.4/site-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/home/goneri/venv/py34/lib/python3.4/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/goneri/git_repos/python-dciclient/dciclient/v1/shell_commands/job.py", line 28, in list
    result = job.list(context)
AttributeError: 'module' object has no attribute 'list'
```

**Comment by leifmadsen** [comment]
Pretty sure this is old, and no longer an issue. Definitely works for me.
