### ISSUE TITLE
file upload fails with api_secret and compressed archive

### ISSUE THREAD

**Issue by dsavineau** [redhat-cip/python-dciclient#7]
Since I switch to auth token instead of login/pass for my remoteci, I have notice that the upload of compressed tarball (via collect-logs role) is not working. Other file upload (plain, junit) is fine.

The python trace returns by the dci file module : 
```
Traceback (most recent call last):
  File "/tmp/ansible_51B0lD/ansible_module_dci_file.py", line 217,
 in <module>
    main()
  File "/tmp/ansible_51B0lD/ansible_module_dci_file.py", line 199, in main
    res = dci_file.create(ctx, **kwargs)
  File "/usr/lib/python2.7/site-packages/dciclient/v1/api/file.py", line 36, in create
    return context.session.post(uri, headers=headers, data=content)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 298, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 500, in prepare_auth
    r = auth(self)
  File "/usr/lib/python2.7/site-packages/dciclient/v1/api/context.py", line 98, in __call__
    payload=r.body)
  File "/usr/lib/python2.7/site-packages/dciclient/v1/auth.py", line 55, in sign
    payload_hash = hashlib.sha256(payload.encode('utf-8')).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
```
The files are compressed tarbar with a bigger size than regular files and are using the mime 'application/x-compressed' :
```
-rw-r--r--. 1 root root 5.1M Jul 21 14:38 overcloud-cephstorage-0.tar.gz
-rw-r--r--. 1 root root 4.8M Jul 21 14:38 overcloud-cephstorage-1.tar.gz
-rw-r--r--. 1 root root 4.7M Jul 21 14:38 overcloud-cephstorage-2.tar.gz
-rw-r--r--. 1 root root 3.8M Jul 21 14:38 overcloud-compute-0.tar.gz
-rw-r--r--. 1 root root 3.8M Jul 21 14:38 overcloud-compute-1.tar.gz
-rw-r--r--. 1 root root 3.8M Jul 21 14:38 overcloud-compute-2.tar.gz
-rw-r--r--. 1 root root 6.8M Jul 21 14:38 overcloud-controller-0.tar.gz
-rw-r--r--. 1 root root 5.4M Jul 21 14:38 overcloud-controller-1.tar.gz
-rw-r--r--. 1 root root 5.5M Jul 21 14:38 overcloud-controller-2.tar.gz
-rw-r--r--. 1 root root  28M Jul 21 14:38 undercloud.tar.gz
```

**Comment by fcharlier** [comment]
Patches available for review:
- https://softwarefactory-project.io/r/9055 <- required for the real fix
- https://softwarefactory-project.io/r/9052 <- the real fix
- https://softwarefactory-project.io/r/9053 <- better handling of files in ansible module
