### ISSUE TITLE
token: some commands depends on context.login

### ISSUE THREAD

**Issue by dsavineau** [redhat-cip/python-dciclient#8]
When using auth based on secret api :
```
# dcictl test-list
Traceback (most recent call last):
  File "/usr/bin/dcictl", line 9, in <module>
    load_entry_point('dciclient==0.3.3', 'console_scripts', 'dcictl')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/dciclient/v1/shell_commands/test.py", line 50, in list
    context, where='name:' + context.login).json()['users'][0]['team_id']
AttributeError: 'DciSignatureContext' object has no attribute 'login'
```
That's because we are using context.login in some function :
```
    team_id = team_id or user.list(
        context, where='name:' + context.login).json()['users'][0]['team_id']
```
context.login is present in user/topic/test/remoteci

**Comment by fcharlier** [comment]
See proposed fix in https://softwarefactory-project.io/r/9577
